name: Release Workflow

on:
  push:
    tags: ["release/*/*"]

jobs:
  app-type:
    name: Determine App types
    runs-on: ubuntu-latest
    outputs:
      app-type-id: ${{ steps.app_type.outputs.APP_TYPE }}
    steps:
      - name: Determine App Type
        id: app_type
        run: |
          APP_TYPE=$(echo "${{ github.ref }}" | cut -d'/' -f4)
          echo "APP_TYPE=${APP_TYPE}" >> $GITHUB_OUTPUT
        shell: bash

  migrate:
    name: migration
    runs-on: ubuntu-latest
    steps:
      - name: Migrated
        run: |
          echo "Migrated ✅ "
        shell: bash

  unified-web:
    name: Unified Web build
    needs: [app-type, migrate]
    runs-on: ubuntu-latest
    if: ${{needs.app-type.outputs.app-type-id == 'unified-web'}}
    steps:
      - name: Deploy to Vercel - Unified Web
        run: |
          echo "Unified Web released ✅ "
        shell: bash

  login:
    name: Login build
    needs: [app-type, migrate]
    runs-on: ubuntu-latest
    if: ${{needs.app-type.outputs.app-type-id == 'login'}}
    steps:
      - name: Deploy to Vercel - Login
        run: |
          echo "Login released ✅ "
        shell: bash
